export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const STATUS_MESSAGE = ["success", "error", "warning", "info"];

export const SET_EVENTS_OWNER = "SET_EVENTS_OWNER";
// export const APPEND_EVENTS_OWNER = "APPEND_EVENTS_OWNER";
export const CLEAR_EVENTS_OWNER = "CLEAR_EVENTS_OWNER";
export const SET_LECTURE_DATA = "SET_LECTURE_DATA";
export const CLEAR_LECTURE_DATA = "CLEAR_LECTURE_DATA";
export const SET_SPEAKER_DATA = "SET_SPEAKER_DATA";
export const CLEAR_SPEAKER_DATA = "CLEAR_SPEAKER_DATA";
export const SET_EVENTPARTNER_DATA = "SET_EVENTPARTNER_DATA";
export const CLEAR_EVENTPARTNER_DATA = "CLEAR_EVENTPARTNER_DATA";
